import type { RecipeMeta } from "../types";

// A recipe is a plain, self-contained Python file:
//   - a metadata header (JSON in comments) recording provenance,
//   - the transform() function generated by the AI,
//   - a CLI entry point so it also runs outside the app:
//       python recipe.py input.csv -o output.csv

const META_START = "# === recipe metadata ===";
const META_END = "# === end recipe metadata ===";
const MAIN_GUARD = 'if __name__ == "__main__":';

export function buildRecipe(script: string, meta: RecipeMeta): string {
  const metaLines = JSON.stringify(meta, null, 2)
    .split("\n")
    .map((l) => `# ${l}`)
    .join("\n");

  const cli = `

${MAIN_GUARD}
    import argparse
    import pandas as pd
    parser = argparse.ArgumentParser(description=${pyString(meta.name)})
    parser.add_argument("input", help="Input CSV or Excel file")
    parser.add_argument("-o", "--output", default="output.csv", help="Output CSV path")
    args = parser.parse_args()
    if args.input.lower().endswith((".xlsx", ".xls")):
        df = pd.read_excel(args.input)
    else:
        df = pd.read_csv(args.input)
    result = transform(df)
    result.to_csv(args.output, index=False)
    print(f"Wrote {len(result)} rows to {args.output}")
`;

  return `${META_START}\n${metaLines}\n${META_END}\n\n${script.trim()}\n${cli}`;
}

function pyString(s: string): string {
  // JSON string literals are valid Python string literals.
  return JSON.stringify(s);
}

export interface ParsedRecipe {
  meta: RecipeMeta | null;
  script: string;
}

/**
 * Parse a .py file back into (metadata, transform script). Returns null if
 * the file doesn't look like a recipe (no transform function).
 */
export function parseRecipe(text: string): ParsedRecipe | null {
  if (!text.includes("def transform")) return null;

  let meta: RecipeMeta | null = null;
  let body = text;

  const start = text.indexOf(META_START);
  const end = text.indexOf(META_END);
  if (start !== -1 && end !== -1 && end > start) {
    const rawMeta = text
      .slice(start + META_START.length, end)
      .split("\n")
      .map((l) => l.replace(/^#\s?/, ""))
      .join("\n");
    try {
      meta = JSON.parse(rawMeta) as RecipeMeta;
    } catch {
      meta = null;
    }
    body = text.slice(end + META_END.length);
  }

  const guardIdx = body.indexOf(MAIN_GUARD);
  const script = (guardIdx === -1 ? body : body.slice(0, guardIdx)).trim();
  return { meta, script };
}
