"""add users.is_admin

Revision ID: 6417c5447ba2
Revises: f4a4296245e8
Create Date: 2026-09-03 09:00:19.153250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6417c5447ba2'
down_revision: Union[str, Sequence[str], None] = 'f4a4296245e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # sa.false() renders per-dialect (FALSE on Postgres, 0 on sqlite). A literal
        # sa.text('0') — what autogenerate emits against sqlite — is rejected by
        # Postgres: 'column is of type boolean but default expression is of type integer'.
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
