"""initial schema

Revision ID: f4a4296245e8
Revises: 
Create Date: 2026-09-03 08:59:53.359102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a4296245e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_ip'), ['ip'], unique=False)

    op.create_table('login_codes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_codes_email'), ['email'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('anon_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anon_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anon_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('recipes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_anon_id', sa.String(length=32), nullable=True),
    sa.Column('owner_user_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('current_version_id', sa.String(length=32), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_anon_id'], ['anon_sessions.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_owner_anon_id'), ['owner_anon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_share_token'), ['share_token'], unique=True)

    op.create_table('recipe_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('recipe_id', sa.String(length=32), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('param_values_json', sa.JSON(), nullable=False),
    sa.Column('inputs_json', sa.JSON(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_versions_recipe_id'), ['recipe_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_versions_recipe_id'))

    op.drop_table('recipe_versions')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_share_token'))
        batch_op.drop_index(batch_op.f('ix_recipes_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_recipes_owner_anon_id'))

    op.drop_table('recipes')
    with op.batch_alter_table('anon_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anon_sessions_user_id'))

    op.drop_table('anon_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('login_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_codes_email'))

    op.drop_table('login_codes')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_ip'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_email'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_created_at'))

    op.drop_table('login_attempts')
    # ### end Alembic commands ###
