import type { RecipeMeta } from "../types";

// A recipe file is a self-documenting `.js`: a metadata header (JSON in comments)
// followed by the transform(inputs, params) function. It round-trips through the
// app — drop the .js back in to reload it. It runs inside Prestidata's runtime
// (Arquero + injected helpers: aq, op, col, parseNumber, plotBar, …), not
// standalone. The metadata delimiters are the parse anchors — keep build/parse
// in sync.

const META_START = "// === recipe metadata ===";
const META_END = "// === end recipe metadata ===";

export function buildRecipe(script: string, meta: RecipeMeta): string {
  const metaLines = JSON.stringify(meta, null, 2)
    .split("\n")
    .map((l) => "// " + l)
    .join("\n");
  return `${META_START}\n${metaLines}\n${META_END}\n\n// Generated by Prestidata — drop this file back into the app to reuse it.\n\n${script.trim()}\n`;
}

export interface ParsedRecipe {
  meta: RecipeMeta | null;
  script: string;
}

/** Parse a .js recipe back into (metadata, transform script). */
export function parseRecipe(text: string): ParsedRecipe | null {
  if (!text.includes("transform")) return null;
  let meta: RecipeMeta | null = null;
  let body = text;

  const start = text.indexOf(META_START);
  const end = text.indexOf(META_END);
  if (start !== -1 && end !== -1 && end > start) {
    const rawMeta = text
      .slice(start + META_START.length, end)
      .split("\n")
      .map((l) => l.replace(/^\/\/\s?/, ""))
      .join("\n");
    try {
      meta = JSON.parse(rawMeta) as RecipeMeta;
    } catch {
      meta = null;
    }
    body = text.slice(end + META_END.length);
  }

  return { meta, script: body.trim() };
}
